export { default as Footer } from "./footer"
export { default as GlobalStyles } from "./GlobalStyles"
export { default as Header } from "./header"
export { default as Layout } from "./layout"
export { default as SEO } from "./seo"
export { default as Image } from "./image"
